#############################################################################
# Makefile for building: pygmy.app/Contents/MacOS/pygmy
# Generated by qmake (3.0) (Qt 5.4.1)
# Project:  pygmy.pro
# Template: app
# Command: /Users/connor/Qt/5.4/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile pygmy.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -std=c++11 -stdlib=libc++ -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I. -I/usr/local/include -I/usr/local/include/freetype2 -I../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers -I../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers -I../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers -I../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../Qt/5.4/clang_64/mkspecs/macx-clang -F/Users/connor/Qt/5.4/clang_64/lib
QMAKE         = /Users/connor/Qt/5.4/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = pygmy1.0.0
DISTDIR = /Users/connor/local/pygmy/.tmp/pygmy1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -stdlib=libc++ -mmacosx-version-min=10.7 -Wl,-rpath,/Users/connor/Qt/5.4/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/connor/Qt/5.4/clang_64/lib -L/usr/local/lib -lftgl -framework QtOpenGL -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/glwidget.cpp \
		src/main.cpp \
		src/mainwindow.cpp \
		src/window.cpp \
		src/core/NewickIO.cpp \
		src/utils/Colour.cpp \
		src/utils/Node.cpp \
		src/utils/Point.cpp \
		src/core/VisualLine.cpp \
		src/core/VisualMarker.cpp \
		src/core/VisualObject.cpp \
		src/core/VisualRect.cpp \
		src/core/VisualTree.cpp \
		src/glUtils/Font.cpp \
		src/core/State.cpp \
		src/core/MetadataInfo.cpp \
		src/utils/ParsimonyCalculator.cpp \
		src/glscrollwrapper.cpp qrc_resources.cpp \
		moc_mainwindow.cpp \
		moc_glwidget.cpp \
		moc_window.cpp
OBJECTS       = glwidget.o \
		main.o \
		mainwindow.o \
		window.o \
		NewickIO.o \
		Colour.o \
		Node.o \
		Point.o \
		VisualLine.o \
		VisualMarker.o \
		VisualObject.o \
		VisualRect.o \
		VisualTree.o \
		Font.o \
		State.o \
		MetadataInfo.o \
		ParsimonyCalculator.o \
		glscrollwrapper.o \
		qrc_resources.o \
		moc_mainwindow.o \
		moc_glwidget.o \
		moc_window.o
DIST          = ../../Qt/5.4/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.4/clang_64/mkspecs/qdevice.pri \
		../../Qt/5.4/clang_64/mkspecs/features/device_config.prf \
		../../Qt/5.4/clang_64/mkspecs/common/shell-unix.conf \
		../../Qt/5.4/clang_64/mkspecs/common/unix.conf \
		../../Qt/5.4/clang_64/mkspecs/common/mac.conf \
		../../Qt/5.4/clang_64/mkspecs/common/macx.conf \
		../../Qt/5.4/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.4/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt/5.4/clang_64/mkspecs/common/clang.conf \
		../../Qt/5.4/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt/5.4/clang_64/mkspecs/qconfig.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.4/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.4/clang_64/mkspecs/features/qt_config.prf \
		../../Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt/5.4/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt/5.4/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.4/clang_64/mkspecs/features/default_pre.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt/5.4/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.4/clang_64/mkspecs/features/default_post.prf \
		../../Qt/5.4/clang_64/mkspecs/features/c++11.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt/5.4/clang_64/mkspecs/features/warn_on.prf \
		../../Qt/5.4/clang_64/mkspecs/features/qt.prf \
		../../Qt/5.4/clang_64/mkspecs/features/resources.prf \
		../../Qt/5.4/clang_64/mkspecs/features/moc.prf \
		../../Qt/5.4/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt/5.4/clang_64/mkspecs/features/uic.prf \
		../../Qt/5.4/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt/5.4/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.4/clang_64/mkspecs/features/exceptions.prf \
		../../Qt/5.4/clang_64/mkspecs/features/yacc.prf \
		../../Qt/5.4/clang_64/mkspecs/features/lex.prf \
		pygmy.pro src/mainwindow.h \
		src/glwidget.h \
		src/window.h \
		src/core/NewickIO.hpp \
		src/utils/Tree.hpp \
		src/utils/TreeTools.hpp \
		src/core/NodePhylo.hpp \
		src/utils/Colour.hpp \
		src/utils/Node.hpp \
		src/utils/Point.hpp \
		src/core/DataTypes.hpp \
		src/utils/Common.hpp \
		src/utils/Error.hpp \
		src/core/VisualLine.hpp \
		src/core/VisualMarker.hpp \
		src/core/VisualObject.hpp \
		src/core/VisualRect.hpp \
		src/core/VisualTree.hpp \
		src/glUtils/ErrorGL.hpp \
		src/glUtils/Font.hpp \
		src/core/State.hpp \
		src/core/MetadataInfo.hpp \
		src/core/Filter.hpp \
		src/utils/ParsimonyCalculator.hpp \
		src/glscrollwrapper.h src/glwidget.cpp \
		src/main.cpp \
		src/mainwindow.cpp \
		src/window.cpp \
		src/core/NewickIO.cpp \
		src/utils/Colour.cpp \
		src/utils/Node.cpp \
		src/utils/Point.cpp \
		src/core/VisualLine.cpp \
		src/core/VisualMarker.cpp \
		src/core/VisualObject.cpp \
		src/core/VisualRect.cpp \
		src/core/VisualTree.cpp \
		src/glUtils/Font.cpp \
		src/core/State.cpp \
		src/core/MetadataInfo.cpp \
		src/utils/ParsimonyCalculator.cpp \
		src/glscrollwrapper.cpp
QMAKE_TARGET  = pygmy
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = pygmy.app/Contents/MacOS/pygmy

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk \
		-std=c++11 \
		-stdlib=libc++ \
		-mmacosx-version-min=10.7 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@test -d pygmy.app/Contents/MacOS/ || mkdir -p pygmy.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: pygmy.pro ../../Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf ../../Qt/5.4/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.4/clang_64/mkspecs/qdevice.pri \
		../../Qt/5.4/clang_64/mkspecs/features/device_config.prf \
		../../Qt/5.4/clang_64/mkspecs/common/shell-unix.conf \
		../../Qt/5.4/clang_64/mkspecs/common/unix.conf \
		../../Qt/5.4/clang_64/mkspecs/common/mac.conf \
		../../Qt/5.4/clang_64/mkspecs/common/macx.conf \
		../../Qt/5.4/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.4/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt/5.4/clang_64/mkspecs/common/clang.conf \
		../../Qt/5.4/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt/5.4/clang_64/mkspecs/qconfig.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.4/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.4/clang_64/mkspecs/features/qt_config.prf \
		../../Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt/5.4/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt/5.4/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.4/clang_64/mkspecs/features/default_pre.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt/5.4/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.4/clang_64/mkspecs/features/default_post.prf \
		../../Qt/5.4/clang_64/mkspecs/features/c++11.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt/5.4/clang_64/mkspecs/features/warn_on.prf \
		../../Qt/5.4/clang_64/mkspecs/features/qt.prf \
		../../Qt/5.4/clang_64/mkspecs/features/resources.prf \
		../../Qt/5.4/clang_64/mkspecs/features/moc.prf \
		../../Qt/5.4/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt/5.4/clang_64/mkspecs/features/uic.prf \
		../../Qt/5.4/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt/5.4/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.4/clang_64/mkspecs/features/exceptions.prf \
		../../Qt/5.4/clang_64/mkspecs/features/yacc.prf \
		../../Qt/5.4/clang_64/mkspecs/features/lex.prf \
		pygmy.pro \
		resources.qrc \
		/Users/connor/Qt/5.4/clang_64/lib/QtOpenGL.framework/QtOpenGL.prl \
		/Users/connor/Qt/5.4/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/connor/Qt/5.4/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/connor/Qt/5.4/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile pygmy.pro
../../Qt/5.4/clang_64/mkspecs/features/spec_pre.prf:
../../Qt/5.4/clang_64/mkspecs/qdevice.pri:
../../Qt/5.4/clang_64/mkspecs/features/device_config.prf:
../../Qt/5.4/clang_64/mkspecs/common/shell-unix.conf:
../../Qt/5.4/clang_64/mkspecs/common/unix.conf:
../../Qt/5.4/clang_64/mkspecs/common/mac.conf:
../../Qt/5.4/clang_64/mkspecs/common/macx.conf:
../../Qt/5.4/clang_64/mkspecs/common/gcc-base.conf:
../../Qt/5.4/clang_64/mkspecs/common/gcc-base-mac.conf:
../../Qt/5.4/clang_64/mkspecs/common/clang.conf:
../../Qt/5.4/clang_64/mkspecs/common/clang-mac.conf:
../../Qt/5.4/clang_64/mkspecs/qconfig.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt/5.4/clang_64/mkspecs/features/qt_functions.prf:
../../Qt/5.4/clang_64/mkspecs/features/qt_config.prf:
../../Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf:
../../Qt/5.4/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../Qt/5.4/clang_64/mkspecs/features/exclusive_builds.prf:
../../Qt/5.4/clang_64/mkspecs/features/default_pre.prf:
../../Qt/5.4/clang_64/mkspecs/features/mac/default_pre.prf:
../../Qt/5.4/clang_64/mkspecs/features/resolve_config.prf:
../../Qt/5.4/clang_64/mkspecs/features/default_post.prf:
../../Qt/5.4/clang_64/mkspecs/features/c++11.prf:
../../Qt/5.4/clang_64/mkspecs/features/mac/sdk.prf:
../../Qt/5.4/clang_64/mkspecs/features/mac/default_post.prf:
../../Qt/5.4/clang_64/mkspecs/features/mac/objective_c.prf:
../../Qt/5.4/clang_64/mkspecs/features/warn_on.prf:
../../Qt/5.4/clang_64/mkspecs/features/qt.prf:
../../Qt/5.4/clang_64/mkspecs/features/resources.prf:
../../Qt/5.4/clang_64/mkspecs/features/moc.prf:
../../Qt/5.4/clang_64/mkspecs/features/unix/opengl.prf:
../../Qt/5.4/clang_64/mkspecs/features/uic.prf:
../../Qt/5.4/clang_64/mkspecs/features/unix/thread.prf:
../../Qt/5.4/clang_64/mkspecs/features/mac/rez.prf:
../../Qt/5.4/clang_64/mkspecs/features/testcase_targets.prf:
../../Qt/5.4/clang_64/mkspecs/features/exceptions.prf:
../../Qt/5.4/clang_64/mkspecs/features/yacc.prf:
../../Qt/5.4/clang_64/mkspecs/features/lex.prf:
pygmy.pro:
resources.qrc:
/Users/connor/Qt/5.4/clang_64/lib/QtOpenGL.framework/QtOpenGL.prl:
/Users/connor/Qt/5.4/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/connor/Qt/5.4/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/connor/Qt/5.4/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile pygmy.pro

qmake_all: FORCE

pygmy.app/Contents/PkgInfo: 
	@test -d pygmy.app/Contents || mkdir -p pygmy.app/Contents
	@$(DEL_FILE) pygmy.app/Contents/PkgInfo
	@echo "APPL????" >pygmy.app/Contents/PkgInfo
pygmy.app/Contents/Resources/empty.lproj: 
	@test -d pygmy.app/Contents/Resources || mkdir -p pygmy.app/Contents/Resources
	@touch pygmy.app/Contents/Resources/empty.lproj
	
pygmy.app/Contents/Info.plist: 
	@test -d pygmy.app/Contents || mkdir -p pygmy.app/Contents
	@$(DEL_FILE) pygmy.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,Ecogenomics.pygmy,g" -e "s,@ICON@,pygmy.icns,g" -e "s,@EXECUTABLE@,pygmy,g" -e "s,@TYPEINFO@,????,g" resources/osx/Info.plist >pygmy.app/Contents/Info.plist
pygmy.app/Contents/Resources/pygmy.icns: resources/images/pygmy.icns
	@test -d pygmy.app/Contents/Resources/ || mkdir -p pygmy.app/Contents/Resources/
	@$(DEL_FILE) pygmy.app/Contents/Resources/pygmy.icns
	@$(COPY_FILE) resources/images/pygmy.icns pygmy.app/Contents/Resources/pygmy.icns

all: Makefile \
		pygmy.app/Contents/PkgInfo \
		pygmy.app/Contents/Resources/empty.lproj \
		pygmy.app/Contents/Info.plist \
		pygmy.app/Contents/Resources/pygmy.icns $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents src/mainwindow.h src/glwidget.h src/window.h src/core/NewickIO.hpp src/utils/Tree.hpp src/utils/TreeTools.hpp src/core/NodePhylo.hpp src/utils/Colour.hpp src/utils/Node.hpp src/utils/Point.hpp src/core/DataTypes.hpp src/utils/Common.hpp src/utils/Error.hpp src/core/VisualLine.hpp src/core/VisualMarker.hpp src/core/VisualObject.hpp src/core/VisualRect.hpp src/core/VisualTree.hpp src/glUtils/ErrorGL.hpp src/glUtils/Font.hpp src/core/State.hpp src/core/MetadataInfo.hpp src/core/Filter.hpp src/utils/ParsimonyCalculator.hpp src/glscrollwrapper.h $(DISTDIR)/
	$(COPY_FILE) --parents src/glwidget.cpp src/main.cpp src/mainwindow.cpp src/window.cpp src/core/NewickIO.cpp src/utils/Colour.cpp src/utils/Node.cpp src/utils/Point.cpp src/core/VisualLine.cpp src/core/VisualMarker.cpp src/core/VisualObject.cpp src/core/VisualRect.cpp src/core/VisualTree.cpp src/glUtils/Font.cpp src/core/State.cpp src/core/MetadataInfo.cpp src/utils/ParsimonyCalculator.cpp src/glscrollwrapper.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r pygmy.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		resources/fonts/impact.ttf \
		resources/fonts/trebuchet.ttf \
		resources/fonts/courier.ttf \
		resources/fonts/georgia.ttf \
		resources/fonts/times.ttf \
		resources/fonts/verdana.ttf \
		resources/fonts/arial.ttf \
		resources/fonts/andale.ttf
	/Users/connor/Qt/5.4/clang_64/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_glwidget.cpp moc_window.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_glwidget.cpp moc_window.cpp
moc_mainwindow.cpp: ../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		src/glscrollwrapper.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QAbstractScrollArea \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractscrollarea.h \
		src/glwidget.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QOpenGLWidget \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qopenglwidget.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QSize \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsize.h \
		src/core/DataTypes.hpp \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QSharedPointer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsharedpointer.h \
		src/core/VisualTree.hpp \
		src/core/NodePhylo.hpp \
		src/utils/Node.hpp \
		src/utils/Common.hpp \
		src/utils/Point.hpp \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		src/utils/Colour.hpp \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QColor \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qcolor.h \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/gl.h \
		src/core/VisualObject.hpp \
		src/core/VisualMarker.hpp \
		src/core/VisualRect.hpp \
		src/utils/Tree.hpp \
		src/utils/TreeTools.hpp \
		src/utils/Error.hpp \
		src/core/Filter.hpp \
		src/glUtils/ErrorGL.hpp \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/glu.h \
		src/mainwindow.h
	/Users/connor/Qt/5.4/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/connor/Qt/5.4/clang_64/mkspecs/macx-clang -I/Users/connor/local/pygmy -I/usr/local/include -I/usr/local/include/freetype2 -I/Users/connor/Qt/5.4/clang_64/lib/QtOpenGL.framework/Headers -I/Users/connor/Qt/5.4/clang_64/lib/QtWidgets.framework/Headers -I/Users/connor/Qt/5.4/clang_64/lib/QtGui.framework/Headers -I/Users/connor/Qt/5.4/clang_64/lib/QtCore.framework/Headers -F/Users/connor/Qt/5.4/clang_64/lib src/mainwindow.h -o moc_mainwindow.cpp

moc_glwidget.cpp: ../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QOpenGLWidget \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qopenglwidget.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QSize \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsize.h \
		src/core/DataTypes.hpp \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QSharedPointer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsharedpointer.h \
		src/core/VisualTree.hpp \
		src/core/NodePhylo.hpp \
		src/utils/Node.hpp \
		src/utils/Common.hpp \
		src/utils/Point.hpp \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		src/utils/Colour.hpp \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QColor \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qcolor.h \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/gl.h \
		src/core/VisualObject.hpp \
		src/core/VisualMarker.hpp \
		src/core/VisualRect.hpp \
		src/utils/Tree.hpp \
		src/utils/TreeTools.hpp \
		src/utils/Error.hpp \
		src/core/Filter.hpp \
		src/glUtils/ErrorGL.hpp \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/glu.h \
		src/glwidget.h
	/Users/connor/Qt/5.4/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/connor/Qt/5.4/clang_64/mkspecs/macx-clang -I/Users/connor/local/pygmy -I/usr/local/include -I/usr/local/include/freetype2 -I/Users/connor/Qt/5.4/clang_64/lib/QtOpenGL.framework/Headers -I/Users/connor/Qt/5.4/clang_64/lib/QtWidgets.framework/Headers -I/Users/connor/Qt/5.4/clang_64/lib/QtGui.framework/Headers -I/Users/connor/Qt/5.4/clang_64/lib/QtCore.framework/Headers -F/Users/connor/Qt/5.4/clang_64/lib src/glwidget.h -o moc_glwidget.cpp

moc_window.cpp: ../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		src/window.h
	/Users/connor/Qt/5.4/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/connor/Qt/5.4/clang_64/mkspecs/macx-clang -I/Users/connor/local/pygmy -I/usr/local/include -I/usr/local/include/freetype2 -I/Users/connor/Qt/5.4/clang_64/lib/QtOpenGL.framework/Headers -I/Users/connor/Qt/5.4/clang_64/lib/QtWidgets.framework/Headers -I/Users/connor/Qt/5.4/clang_64/lib/QtGui.framework/Headers -I/Users/connor/Qt/5.4/clang_64/lib/QtCore.framework/Headers -F/Users/connor/Qt/5.4/clang_64/lib src/window.h -o moc_window.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/Users/connor/Qt/5.4/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

glwidget.o: src/glwidget.cpp src/glwidget.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QOpenGLWidget \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qopenglwidget.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QSize \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsize.h \
		src/core/DataTypes.hpp \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QSharedPointer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsharedpointer.h \
		src/core/VisualTree.hpp \
		src/core/NodePhylo.hpp \
		src/utils/Node.hpp \
		src/utils/Common.hpp \
		src/utils/Point.hpp \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		src/utils/Colour.hpp \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QColor \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qcolor.h \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/gl.h \
		src/core/VisualObject.hpp \
		src/core/VisualMarker.hpp \
		src/core/VisualRect.hpp \
		src/utils/Tree.hpp \
		src/utils/TreeTools.hpp \
		src/utils/Error.hpp \
		src/core/Filter.hpp \
		src/glUtils/ErrorGL.hpp \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/glu.h \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QMouseEvent \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QOpenGLShaderProgram \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglshaderprogram.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QCoreApplication \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qcoreapplication.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QtDebug \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		src/core/State.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o glwidget.o src/glwidget.cpp

main.o: src/main.cpp ../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QApplication \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDesktopWidget \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdesktopwidget.h \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QSurfaceFormat \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qsurfaceformat.h \
		src/mainwindow.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		src/glscrollwrapper.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QAbstractScrollArea \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractscrollarea.h \
		src/glwidget.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QOpenGLWidget \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qopenglwidget.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QSize \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsize.h \
		src/core/DataTypes.hpp \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QSharedPointer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsharedpointer.h \
		src/core/VisualTree.hpp \
		src/core/NodePhylo.hpp \
		src/utils/Node.hpp \
		src/utils/Common.hpp \
		src/utils/Point.hpp \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		src/utils/Colour.hpp \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QColor \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qcolor.h \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/gl.h \
		src/core/VisualObject.hpp \
		src/core/VisualMarker.hpp \
		src/core/VisualRect.hpp \
		src/utils/Tree.hpp \
		src/utils/TreeTools.hpp \
		src/utils/Error.hpp \
		src/core/Filter.hpp \
		src/glUtils/ErrorGL.hpp \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/glu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

mainwindow.o: src/mainwindow.cpp src/mainwindow.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		src/glscrollwrapper.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QAbstractScrollArea \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractscrollarea.h \
		src/glwidget.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QOpenGLWidget \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qopenglwidget.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QSize \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsize.h \
		src/core/DataTypes.hpp \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QSharedPointer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsharedpointer.h \
		src/core/VisualTree.hpp \
		src/core/NodePhylo.hpp \
		src/utils/Node.hpp \
		src/utils/Common.hpp \
		src/utils/Point.hpp \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		src/utils/Colour.hpp \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QColor \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qcolor.h \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/gl.h \
		src/core/VisualObject.hpp \
		src/core/VisualMarker.hpp \
		src/core/VisualRect.hpp \
		src/utils/Tree.hpp \
		src/utils/TreeTools.hpp \
		src/utils/Error.hpp \
		src/core/Filter.hpp \
		src/glUtils/ErrorGL.hpp \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/glu.h \
		src/core/NewickIO.hpp \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTextStream \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtextstream.h \
		src/core/State.hpp \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenuBar \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenubar.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenu \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenu.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QFileDialog \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfiledialog.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDockWidget \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdockwidget.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QStackedLayout \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qstackedlayout.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QScrollBar \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qscrollbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o src/mainwindow.cpp

window.o: src/window.cpp src/glwidget.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QOpenGLWidget \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qopenglwidget.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QSize \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsize.h \
		src/core/DataTypes.hpp \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QSharedPointer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsharedpointer.h \
		src/core/VisualTree.hpp \
		src/core/NodePhylo.hpp \
		src/utils/Node.hpp \
		src/utils/Common.hpp \
		src/utils/Point.hpp \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		src/utils/Colour.hpp \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QColor \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qcolor.h \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/gl.h \
		src/core/VisualObject.hpp \
		src/core/VisualMarker.hpp \
		src/core/VisualRect.hpp \
		src/utils/Tree.hpp \
		src/utils/TreeTools.hpp \
		src/utils/Error.hpp \
		src/core/Filter.hpp \
		src/glUtils/ErrorGL.hpp \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/glu.h \
		src/window.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		src/mainwindow.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		src/glscrollwrapper.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QAbstractScrollArea \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractscrollarea.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QSlider \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qslider.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QVBoxLayout \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qboxlayout.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QHBoxLayout \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QKeyEvent \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QPushButton \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qpushbutton.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDesktopWidget \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdesktopwidget.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QApplication \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o window.o src/window.cpp

NewickIO.o: src/core/NewickIO.cpp src/core/NewickIO.hpp \
		src/core/NodePhylo.hpp \
		src/utils/Node.hpp \
		src/utils/Common.hpp \
		src/utils/Point.hpp \
		src/core/DataTypes.hpp \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QSharedPointer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsharedpointer.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		src/utils/Colour.hpp \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QColor \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qcolor.h \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/gl.h \
		src/utils/Tree.hpp \
		src/utils/TreeTools.hpp \
		src/utils/Error.hpp \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTextStream \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtextstream.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFileInfo \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfileinfo.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QRegularExpression \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qregularexpression.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QtDebug \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NewickIO.o src/core/NewickIO.cpp

Colour.o: src/utils/Colour.cpp src/utils/Colour.hpp \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QColor \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qcolor.h \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/gl.h \
		src/core/DataTypes.hpp \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QSharedPointer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsharedpointer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Colour.o src/utils/Colour.cpp

Node.o: src/utils/Node.cpp src/utils/Node.hpp \
		src/utils/Common.hpp \
		src/utils/Point.hpp \
		src/core/DataTypes.hpp \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QSharedPointer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsharedpointer.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		src/utils/Error.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Node.o src/utils/Node.cpp

Point.o: src/utils/Point.cpp src/utils/Point.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Point.o src/utils/Point.cpp

VisualLine.o: src/core/VisualLine.cpp src/core/VisualLine.hpp \
		src/core/VisualObject.hpp \
		src/utils/Colour.hpp \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QColor \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qcolor.h \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/gl.h \
		src/core/DataTypes.hpp \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QSharedPointer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsharedpointer.h \
		src/utils/Point.hpp \
		src/utils/Line.hpp \
		src/glUtils/ErrorGL.hpp \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/glu.h \
		src/utils/Error.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o VisualLine.o src/core/VisualLine.cpp

VisualMarker.o: src/core/VisualMarker.cpp src/core/VisualMarker.hpp \
		src/core/VisualObject.hpp \
		src/utils/Colour.hpp \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QColor \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qcolor.h \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/gl.h \
		src/core/DataTypes.hpp \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QSharedPointer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsharedpointer.h \
		src/utils/Point.hpp \
		src/glUtils/ErrorGL.hpp \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/glu.h \
		src/utils/Error.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o VisualMarker.o src/core/VisualMarker.cpp

VisualObject.o: src/core/VisualObject.cpp src/core/VisualObject.hpp \
		src/utils/Colour.hpp \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QColor \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qcolor.h \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/gl.h \
		src/core/DataTypes.hpp \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QSharedPointer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsharedpointer.h \
		src/utils/Point.hpp \
		src/glUtils/ErrorGL.hpp \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/glu.h \
		src/utils/Error.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o VisualObject.o src/core/VisualObject.cpp

VisualRect.o: src/core/VisualRect.cpp src/core/VisualRect.hpp \
		src/core/VisualObject.hpp \
		src/utils/Colour.hpp \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QColor \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qcolor.h \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/gl.h \
		src/core/DataTypes.hpp \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QSharedPointer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsharedpointer.h \
		src/utils/Point.hpp \
		src/utils/Common.hpp \
		src/glUtils/ErrorGL.hpp \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/glu.h \
		src/utils/Error.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o VisualRect.o src/core/VisualRect.cpp

VisualTree.o: src/core/VisualTree.cpp src/core/VisualTree.hpp \
		src/core/NodePhylo.hpp \
		src/utils/Node.hpp \
		src/utils/Common.hpp \
		src/utils/Point.hpp \
		src/core/DataTypes.hpp \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QSharedPointer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsharedpointer.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		src/utils/Colour.hpp \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QColor \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qcolor.h \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/gl.h \
		src/core/VisualObject.hpp \
		src/core/VisualMarker.hpp \
		src/core/VisualRect.hpp \
		src/utils/Tree.hpp \
		src/utils/TreeTools.hpp \
		src/utils/Error.hpp \
		src/core/Filter.hpp \
		src/core/VisualColourMap.hpp \
		src/core/State.hpp \
		src/core/MetadataInfo.hpp \
		src/glUtils/ErrorGL.hpp \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/glu.h \
		src/glUtils/Font.hpp \
		/usr/local/include/FTGL/ftgl.h \
		/usr/local/include/freetype2/ft2build.h \
		/usr/local/include/freetype2/config/ftheader.h \
		/usr/local/include/FTGL/FTPoint.h \
		/usr/local/include/FTGL/FTBBox.h \
		/usr/local/include/FTGL/FTBuffer.h \
		/usr/local/include/FTGL/FTGlyph.h \
		/usr/local/include/FTGL/FTBitmapGlyph.h \
		/usr/local/include/FTGL/FTBufferGlyph.h \
		/usr/local/include/FTGL/FTExtrdGlyph.h \
		/usr/local/include/FTGL/FTOutlineGlyph.h \
		/usr/local/include/FTGL/FTPixmapGlyph.h \
		/usr/local/include/FTGL/FTPolyGlyph.h \
		/usr/local/include/FTGL/FTTextureGlyph.h \
		/usr/local/include/FTGL/FTFont.h \
		/usr/local/include/FTGL/FTGLBitmapFont.h \
		/usr/local/include/FTGL/FTBufferFont.h \
		/usr/local/include/FTGL/FTGLExtrdFont.h \
		/usr/local/include/FTGL/FTGLOutlineFont.h \
		/usr/local/include/FTGL/FTGLPixmapFont.h \
		/usr/local/include/FTGL/FTGLPolygonFont.h \
		/usr/local/include/FTGL/FTGLTextureFont.h \
		/usr/local/include/FTGL/FTLayout.h \
		/usr/local/include/FTGL/FTSimpleLayout.h \
		src/utils/Geometry.hpp \
		src/utils/Line.hpp \
		src/utils/ColourMap.hpp \
		src/utils/ColourMapDiscrete.hpp \
		src/utils/ColourMapContinuous.hpp \
		src/utils/ParsimonyCalculator.hpp \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QtDebug \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QOpenGLContext \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglcontext.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o VisualTree.o src/core/VisualTree.cpp

Font.o: src/glUtils/Font.cpp src/glUtils/Font.hpp \
		src/utils/Common.hpp \
		src/utils/Point.hpp \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		/usr/local/include/FTGL/ftgl.h \
		/usr/local/include/freetype2/ft2build.h \
		/usr/local/include/freetype2/config/ftheader.h \
		/usr/local/include/FTGL/FTPoint.h \
		/usr/local/include/FTGL/FTBBox.h \
		/usr/local/include/FTGL/FTBuffer.h \
		/usr/local/include/FTGL/FTGlyph.h \
		/usr/local/include/FTGL/FTBitmapGlyph.h \
		/usr/local/include/FTGL/FTBufferGlyph.h \
		/usr/local/include/FTGL/FTExtrdGlyph.h \
		/usr/local/include/FTGL/FTOutlineGlyph.h \
		/usr/local/include/FTGL/FTPixmapGlyph.h \
		/usr/local/include/FTGL/FTPolyGlyph.h \
		/usr/local/include/FTGL/FTTextureGlyph.h \
		/usr/local/include/FTGL/FTFont.h \
		/usr/local/include/FTGL/FTGLBitmapFont.h \
		/usr/local/include/FTGL/FTBufferFont.h \
		/usr/local/include/FTGL/FTGLExtrdFont.h \
		/usr/local/include/FTGL/FTGLOutlineFont.h \
		/usr/local/include/FTGL/FTGLPixmapFont.h \
		/usr/local/include/FTGL/FTGLPolygonFont.h \
		/usr/local/include/FTGL/FTGLTextureFont.h \
		/usr/local/include/FTGL/FTLayout.h \
		/usr/local/include/FTGL/FTSimpleLayout.h \
		src/glUtils/ErrorGL.hpp \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/glu.h \
		src/utils/Error.hpp \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QByteArray \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qbytearray.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QtDebug \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Font.o src/glUtils/Font.cpp

State.o: src/core/State.cpp src/core/State.hpp \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		src/utils/Point.hpp \
		src/utils/Colour.hpp \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QColor \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qcolor.h \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/gl.h \
		src/core/DataTypes.hpp \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QSharedPointer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsharedpointer.h \
		src/glUtils/Font.hpp \
		src/utils/Common.hpp \
		/usr/local/include/FTGL/ftgl.h \
		/usr/local/include/freetype2/ft2build.h \
		/usr/local/include/freetype2/config/ftheader.h \
		/usr/local/include/FTGL/FTPoint.h \
		/usr/local/include/FTGL/FTBBox.h \
		/usr/local/include/FTGL/FTBuffer.h \
		/usr/local/include/FTGL/FTGlyph.h \
		/usr/local/include/FTGL/FTBitmapGlyph.h \
		/usr/local/include/FTGL/FTBufferGlyph.h \
		/usr/local/include/FTGL/FTExtrdGlyph.h \
		/usr/local/include/FTGL/FTOutlineGlyph.h \
		/usr/local/include/FTGL/FTPixmapGlyph.h \
		/usr/local/include/FTGL/FTPolyGlyph.h \
		/usr/local/include/FTGL/FTTextureGlyph.h \
		/usr/local/include/FTGL/FTFont.h \
		/usr/local/include/FTGL/FTGLBitmapFont.h \
		/usr/local/include/FTGL/FTBufferFont.h \
		/usr/local/include/FTGL/FTGLExtrdFont.h \
		/usr/local/include/FTGL/FTGLOutlineFont.h \
		/usr/local/include/FTGL/FTGLPixmapFont.h \
		/usr/local/include/FTGL/FTGLPolygonFont.h \
		/usr/local/include/FTGL/FTGLTextureFont.h \
		/usr/local/include/FTGL/FTLayout.h \
		/usr/local/include/FTGL/FTSimpleLayout.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QCoreApplication \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qcoreapplication.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QSettings \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsettings.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QDir \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdir.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o State.o src/core/State.cpp

MetadataInfo.o: src/core/MetadataInfo.cpp src/core/MetadataInfo.hpp \
		src/core/NodePhylo.hpp \
		src/utils/Node.hpp \
		src/utils/Common.hpp \
		src/utils/Point.hpp \
		src/core/DataTypes.hpp \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QSharedPointer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsharedpointer.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		src/utils/Colour.hpp \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QColor \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qcolor.h \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/gl.h \
		src/utils/Tree.hpp \
		src/utils/TreeTools.hpp \
		src/utils/Error.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MetadataInfo.o src/core/MetadataInfo.cpp

ParsimonyCalculator.o: src/utils/ParsimonyCalculator.cpp src/utils/ParsimonyCalculator.hpp \
		src/utils/Tree.hpp \
		src/utils/TreeTools.hpp \
		src/utils/Error.hpp \
		src/utils/Node.hpp \
		src/utils/Common.hpp \
		src/utils/Point.hpp \
		src/core/DataTypes.hpp \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QSharedPointer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsharedpointer.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		src/core/NodePhylo.hpp \
		src/utils/Colour.hpp \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QColor \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qcolor.h \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/gl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ParsimonyCalculator.o src/utils/ParsimonyCalculator.cpp

glscrollwrapper.o: src/glscrollwrapper.cpp src/glscrollwrapper.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QAbstractScrollArea \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qabstractscrollarea.h \
		src/glwidget.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QOpenGLWidget \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qopenglwidget.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QSize \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsize.h \
		src/core/DataTypes.hpp \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QSharedPointer \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsharedpointer.h \
		src/core/VisualTree.hpp \
		src/core/NodePhylo.hpp \
		src/utils/Node.hpp \
		src/utils/Common.hpp \
		src/utils/Point.hpp \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		src/utils/Colour.hpp \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QColor \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qcolor.h \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/gl.h \
		src/core/VisualObject.hpp \
		src/core/VisualMarker.hpp \
		src/core/VisualRect.hpp \
		src/utils/Tree.hpp \
		src/utils/TreeTools.hpp \
		src/utils/Error.hpp \
		src/core/Filter.hpp \
		src/glUtils/ErrorGL.hpp \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/glu.h \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QResizeEvent \
		../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QtDebug \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QScrollBar \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qscrollbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o glscrollwrapper.o src/glscrollwrapper.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_glwidget.o: moc_glwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_glwidget.o moc_glwidget.cpp

moc_window.o: moc_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_window.o moc_window.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

